import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  voidchestSidebar: [{type: 'autogenerated', dirName: 'voidchest'}],

};

export default sidebars;
